version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  apt_packages:
    - gcc

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Explicitly set the version of Python and its requirements
python:
  install:
    - requirements: requirements-docs.txt
