version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"

  apt_packages:
    # Install necessary system-level dependencies
    - gcc
    - python3-dev
    - build-essential 

sphinx:
  configuration: docs/conf.py 

python:
  install:
    - requirements: requirements-docs.txt 

commands:
  - pip install --upgrade pip setuptools wheel
  - pip install pyzmq --no-binary=:all:
