version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  apt_packages:
    - build-essential
    - libzmq3-dev 
    - gcc
    - g++
    - python3-dev
    
sphinx:
  configuration: docs/conf.py 
  
python:
  install:
    - requirements: requirements-docs.txt
