version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"

  apt_packages:
    # Install necessary system-level dependencies
    - gcc
    - python3-dev
    - build-essential 

sphinx:
  configuration: docs/conf.py 

python:
  install:
    - method: pip
      path: .
    - requirements: requirements-docs.txt 
    - method: pip
      args: --upgrade pip setuptools wheel  
    - method: pip
      args: pyzmq --no-binary=:all: 
